[DBCredentials]
USER=vladyslav
PASS=fjru47&
; DB_NAME=quotes
DB_NAME=quotes3
DOMAIN=vprogdb.wstfbh3.mongodb.net

[DEFAULT]
ServerAliveInterval = 45
Compression = yes
CompressionLevel = 9
ForwardX11 = yes

[forge.example]
User = hg

[topsecret.server.example]
Port = 50022
ForwardX11 = no